Refactor scripts

diff --git a/bin/bootstrap b/bin/bootstrap
--- a/bin/bootstrap
+++ b/bin/bootstrap
@@ -2,12 +2,12 @@
 
 bin/branding
 
-if ! command -v ruby >/dev/null; then
-  echo "Ruby is not installed. Cannot proceed."
+if [ -z "$(command -v ruby)" ]; then
+  echo "Ruby is not installed. Cannot proceed." >&2
   exit 1
 fi
 
-if ! command -v bundle >/dev/null; then
+if [ -z "$(command -v bundle)" ]; then
   echo "Bundler is not installed. Installing..."
   if [ -f Gemfile.lock ] && grep "BUNDLED WITH" Gemfile.lock >/dev/null; then
     gem install bundler -v "$(grep 'BUNDLED WITH' -A1 Gemfile.lock | tail -n 1)"
@@ -18,13 +18,13 @@ if [ -f Gemfile ]; then
   bundle install
 fi
 
-if ! command -v node >/dev/null; then
-  echo "Node is not installed. Cannot proceed."
+if [ -z "$(command -v node)" ]; then
+  echo "Node is not installed. Cannot proceed." >&2
   exit 1
 fi
 
-if ! command -v npm >/dev/null; then
-  echo "npm command not found. Cannot proceed."
+if [ -z "$(command -v npm)" ]; then
+  echo "npm command not found. Cannot proceed." >&2
   exit 1
 fi
 
diff --git a/bin/html_proofer b/bin/html_proofer
--- a/bin/html_proofer
+++ b/bin/html_proofer
@@ -1,7 +1,9 @@
 #!/bin/bash
 
-if ! command -v htmlproofer >/dev/null; then
-  echo "html_proofer gem not installed. Cannot proceed."
+set -euo pipefail
+
+if [ -z "$(command -v htmlproofer)" ]; then
+  echo "html_proofer gem not installed. Cannot proceed." >&2
   exit 1
 fi
 
@@ -12,5 +14,10 @@ ignore_urls=$(awk -vORS=, '{ print $1 }' .cloudflare/_redirects | sed 's/\*//g')
 #sed 's/,$//'
 
 echo "HTMLProofer $(bundle exec htmlproofer --version)"
-bundle exec jekyll build
+
+if ! [ -d _site ]; then
+  echo "Jekyll build directory not found. Building..."
+  bundle exec jekyll build
+fi
+
 htmlproofer --check_sri --disable_external --ignore-urls \""$ignore_urls"\" $build_dir
